sudo: required

language: generic

services:
  - docker

before_script:  
  - curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o /usr/local/bin/dgoss | sudo sh
  
install:
  - docker build -t zeroboh/php:7.1 .

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push zeroboh/php:7.1
